#!/bin/bash
# Written by lithid (mrlithid@gmail.com)
. $CMC_HOME/tools/f/compile_functions
REM_BACK="$CMC_BACKUP/remove_cyanogenmod_wallpapers"
if [ ! -d $REM_BACK ]; then
	mkdir -p $REM_BACK
fi
echo "	Removed cyanogen wallpapers" >> $CMC_DELETED

function backup_file() {
cp $F_EDIT $REM_BACK/$UNIQ
rm -rf $F_EDIT
touch $F_EDIT
echo "cp $REM_BACK/$UNIQ $F_EDIT" >> $CMC_RESTORE
}

UNIQ=$(echo `</dev/urandom tr -dc A-Za-z0-9 | head -c20`)
F_EDIT="$REPO_PATH/vendor/cyanogen/products/common_full.mk"
backup_file

(cat << EOF) > $REPO_PATH/vendor/cyanogen/products/common_full.mk

# Inherit common CM stuff
\$(call inherit-product, vendor/cyanogen/products/common.mk)

# Bring in all audio files
include frameworks/base/data/sounds/AllAudio.mk

# Theme packages
include vendor/cyanogen/products/themes.mk

# Include extra dictionaries for LatinIME
PRODUCT_PACKAGE_OVERLAYS += vendor/cyanogen/overlay/dictionaries

# Default ringtone
PRODUCT_PROPERTY_OVERRIDES += \\
    ro.config.ringtone=Playa.ogg \\
    ro.config.notification_sound=regulus.ogg \\
    ro.config.alarm_alert=Alarm_Beep_03.ogg
EOF